gazebo_ros_control:
  pid_gains:
    joint1:
      p: 100.0
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    joint2:
      p: 100.0
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    joint3:
      p: 100.0
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    joint4:
      p: 100.0
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    gripper:
      p: 100.0
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true
    gripper_sub:
      p: 100.0
      i: 0.1
      d: 1.0
      i_clamp: 0.2
      antiwindup: false
      publish_state: true

